Development:
  ###
  # This parameter is used to activate or deactivate the debug mode.
  DEBUG_FLAG: 0             # 1 ... activate 0 ... deactivate
  USE_GPU: 1

PreProcessing:
  ###
  # This flag is used to to specify the resize dimension. (only usable if DOWNSCALE_FLAG is active).
  RESIZE_DIM: 128, 128      # resize dimension -> height, width
  ###
  # This flag is used to convert a input frame into a grayscale frame (0... deactivate, 1 ... activate).
  CONVERT2GRAY: 0           # 0 or 1   --> not working yet
  ###
  # This flag is used to center crop a input frame (0... deactivate, 1 ... activate).
  CROP: 1                   # 0 or 1
  ###
  # This flag is used to scale a input frame into the specified dimension (0... deactivate, 1 ... activate).
  DOWNSCALE: 1              # 0 or 1
  ###
  # This parameter is used to to specify a valid pre-processing method (clahe" or "classic" or "none).
  HISTOGRAM_EQU: 'none'     # "clahe" or "classic" or "none"

SbdCore:
  ###
  # This flag is used to to enable or disable the candidate selection mode.
  CANDIDATE_SELECTION: 0    # 1 ... activate 0 ... deactivate

  ###
  # This parameter is used to save raw results (e.g. debug visualizations).
  SAVE_RAW_RESULTS: 0       # 1 ... yes 0 ... no
  ###
  # This parameter is used to specify the path for saving the raw results.
  PATH_RAW_RESULTS: "results/sbd/raw_results/"
  ###
  # This parameter is used to specify the prefix for the results file.
  PREFIX_RAW_RESULTS: "results_raw_"
  ###
  # This parameter is used to specify the postfix for the results file.
  POSTFIX_RAW_RESULTS: "csv"

  ###
  # This parameter is used to save final results (e.g. csv list).
  SAVE_FINAL_RESULTS: 1     # 1 ... yes 0 ... no
  ###
  # This parameter is used to specify the path for saving the final results.
  PATH_FINAL_RESULTS: "/data/share/fjogl/vhh_core_workspace/results/sbd/final_results/"
  ###
  # This parameter is used to specify the prefix for the results file.
  PREFIX_FINAL_RESULTS: ""
  ###
  # This parameter is used to specify the postfix for the results file.
  POSTFIX_FINAL_RESULTS: "csv"

  ###
  # This parameter is used to specify the path to the videos.
  PATH_VIDEOS: "/data/share/fjogl/vhh_core_workspace/videos/"
  ###
  # This parameter is used to specify the threshold mode (adaptive OR fixed).
  THRESHOLD_MODE: 'adaptive'    # adaptive OR fixed
  ###
  # This parameter is used to specify the threshold (only in fixed threshold mode - [0-1]).
  THRESHOLD: 0.8                 # value [0-1]  --> FIXED MODE
  ###
  # This parameter is used to specify the threshold (only in adaptive threshold mode).
  ALPHA: 0.4                     # value > 1   
  ###
  # This parameter is used to specify the threshold (only in adaptive threshold mode).
  BETA: 0.5                  # value [0-1]
  ###
  # This parameter is used to specify the window size (frames history window - only for adaptive mode).
  WINDOW_SIZE: 50               # only for adaptive mode
  ###
  # This parameter is used to specify the backbone cnn model ( vgg16 OR squeezenet).
  BACKBONE_CNN: "squeezenet"    # vgg16 OR squeezenet
  ###
  # This parameter is used to specify the similarity metric (cosine OR euclidean).
  SIMILARITY_METRIC: "cosine"

CandidateSelection:
  ###
  # This parameter is used to specify the path to the pre-trained model.
  PATH_PRETRAINED_MODEL: "models/sbd/Alexnet-final.pth"

Evaluation:
  ###
  # This parameter is used to save evaluation results (e.g. visualizations, ... ).
  SAVE_EVAL_RESULTS: 0
  ###
  # This parameter is used the raw results path.
  PATH_RAW_RESULTS: "results/sbd/raw_results/"
  ###
  # This parameter is used to specify the path to store the evaluation results path.
  PATH_EVAL_RESULTS: "results/sbd/develop/"
  ###
  # This parameter is used to groundtruth annotations used for evaluation.
  PATH_GT_ANNOTATIONS: "/caa/Projects02/vhh/private/database_nobackup/VHH_datasets/annotations/ShotBoundaryDetection/imediacities/sbd_imc_annotations_20191231.csv"
