Development:
  ###
  # This parameter is used to activate or deactivate the debug mode.
  DEBUG_FLAG: 0             # 1 ... activate 0 ... deactivate

Security:
  ###
  # This parameter specifies the path tp the certificate file needed to provide vhh-mmsi api access.
  PEM_PATH: "/home/dhelm/VHH_Releases/certificates/cacert.pem"  # certificate file for vhh-mmsi api access

ApiEndpoints:
  ###
  # This parameter specifies the root url for the RestApi endpoints.
  ROOT_URL: "https://api.vhh-mmsi.eu/api/tbaservice/"   # root url for API endpoints

VhhCore:
  ###
  # This parameter specifies the video download path.
  VIDEO_DOWNLOAD_PATH: "videos/"   # directory to store all downloaded videos
  
  ###
  # This parameter specifies the path to the pre-trained models.
  PRETRAINED_MODEL_PATH: "models/"   # directory to store all downloaded videos

  ###
  # This parameter is used to activate/deactivate the clean-up mode. The clean-up mode deletes all downloaded videos and the corresponding generated results.
  CLEANUP_FLAG: 0   # 0 ... deactivate cleanup function OR 1 ... activate cleanup method -> delete all downloaded videos + annotation results locally

  ###
  # This parameter specifies the results path for each individual plugin.
  # TODO: this needs to be adjusted (along with other configs?)
  RESULTS_ROOT_DIR: "results/"

  ###
  # This parameter specifies the size of the processed videos within one cycle (e.g. size 2 means that 2 videos will be downloaded and processed. 
  # if the results are generated, the next 2 videos will be downloaded and processed.).
  BATCH_PROCESSING_SIZE: 2
  
  ###
  # This parameter specifies the format in which the results are written.
  # CSV_LOCAL ... writes results to RESULTS_ROOT_DIR/core/results.csv
  # JSON_LOCAL ... writes results to RESULTS_ROOT_DIR/core/results.json
  # JSON_REST ... uses the Rest API to publish results as JSON files
  # other ... do not write any results
  RESULTS_FORMAT: "CSV_LOCAL"

PluginConfigs:
  ###
  # This parameter is used to activate or deactivate the SBD Plugin
  USE_SBD: 0             # 1 ... activate 0 ... deactivate
  # This parameter specifies the configuration path (.yaml) for the shot boundary detection plugin module
  SBD_CONFIG_FILE: "config/SBD/config_sbd.yaml"

  ###
  # This parameter is used to activate or deactivate the STC Plugin
  USE_STC: 0             # 1 ... activate 0 ... deactivate
  # This parameter specifies the configuration path (.yaml) for the shot type classification plugin module
  STC_CONFIG_FILE: "config/STC/config_stc.yaml"

  ###
  # This parameter is used to activate or deactivate the CMC Plugin
  USE_CMC: 0             # 1 ... activate 0 ... deactivate
  # This parameter specifies the configuration path (.yaml) for the camera movement classification module
  CMC_CONFIG_FILE: "config/CMC/config_cmc.yaml"

  ###
  # This parameter is used to activate or deactivate the ODT Plugin
  USE_ODT: 1             # 1 ... activate 0 ... deactivate
  # This parameter specifies the configuration path (.yaml) for the object detection and tracking module
  ODT_CONFIG_FILE: "config/ODT/config_od.yaml"





